import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/providers/Header";
import Clerk from "@/components/providers/Clerk";
import { Toaster } from "@/components/ui/sonner"



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Clerk>
      <body
        className=" min-h-screen bg-gray-50"
      >
        <Header/>

        <main className=" container mx-auto px-4 py-8">
   {children}
        </main>
     
      </body>
      </Clerk>

      <Toaster position="bottom-right"/>
    </html>
  );
}
